# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.20"
src = "src"
test = "test"
libs = ["node_modules", "dependencies"]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.5/src/",
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts-5.0.2/contracts/",
    "@BoringSolidity/=dependencies/BoringSolidity-1.0.0/contracts",
    "@solmate/=dependencies/solmate-6.2.0/src/",
    "@abracadabra/=dependencies/abracadabra-0.0.1/src/",
    "@chainlink/=dependencies/chainlink-0.0.1/src",
]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[dependencies]
"forge-std" = { version = "1.9.5", git = "https://github.com/foundry-rs/forge-std.git", rev = "b93cf4bc34ff214c099dc970b153f85ade8c9f66" }
"solmate" = { version = "6.2.0", git = "https://github.com/transmissions11/solmate.git", rev = "97bdb2003b70382996a79a406813f76417b1cf90" }
"openzeppelin-contracts" = { version = "5.0.2", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "dbb6104ce834628e473d2173bbc9d47f81a9eec3" }
"BoringSolidity" = { version = "1.0.0", git = "https://github.com/Abracadabra-money/BoringSolidity.git", rev = "16e10d3faa1a5eda32668619b6c560e925d85255" }
"abracadabra" = { version = "0.0.1", git = "https://github.com/Abracadabra-money/abracadabra-money-contracts.git", rev = "6021168" }
"chainlink" = { version = "0.0.1", git = "https://github.com/smartcontractkit/foundry-chainlink-toolkit.git", rev = "d610ec9" }

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
base = { key = "${API_KEY_BASESCAN}", url = "https://api.basescan.org/api" }
sepolia = { key = "${API_KEY_ETHERSCAN}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }
bsc = { key = "${API_KEY_BSCSCAN}", url = "https://api.bscscan.com/api" }
bsctestnet = { key = "${API_KEY_BSCSCAN}", url = "https://data-seed-prebsc-1-s1.binance.org:8545" }

[rpc_endpoints]
arbitrum = "https://arbitrum-one-rpc.publicnode.com"
avalanche = "https://avalanche-c-chain-rpc.publicnode.com"
base = "https://mainnet.base.org"
bsc = "https://bsc-dataseed.binance.org"
bsctestnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
gnosis_chain = "https://rpc.gnosischain.com"
localhost = "http://localhost:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://optimism-rpc.publicnode.com"
polygon = "https://polygon-bor-rpc.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
